---
- name: update rsyslog server clients
  lineinfile:
    path: '{{ rsyslog_conf_dir }}/{{ rsyslog_custom_conf_file }}'
    insertafter: 'PermittedPeer=\['
    line: '"{{ rsyslog_client_hostname }}",'
  delegate_to: '{{ rsyslog_server_hostname }}'
  remote_user: root
  when: rsyslog_server_clients_update

- name: restart rsyslog server
  service:
    name: rsyslog
    state: restarted
  delegate_to: '{{ rsyslog_server_hostname }}'
  remote_user: root
  when: rsyslog_server_clients_update

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
